[platformio]
src_dir = firmware

[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
lib_ldf_mode = chain+
lib_extra_dirs = firmware/common
build_flags =
	-Ifirmware/common
lib_deps =
	fastled/FastLED @ ^3.10.3
    functionpointer/arduino-MLX90393 @ ^1.0.2
	br3ttb/PID @ ^1.2.1


[env:motherboard]
extends = env
build_src_filter = +<motherboard/src/> -<arm/> +<common/>


[env:arm]
extends = env
build_src_filter = +<arm/src/> -<motherboard/> +<common/>